server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router: todas las rutas van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al backend
    location /api/ {
        proxy_pass https://front-production-f1d2.up.railway.app/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        
        # Importante: prevenir que nginx convierte POST en GET después de redirecciones
        proxy_redirect off;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
